SELECT FACT_PRICING_RULE.rule_id
       ,FACT_PRICING_RULE.price
       ,FACT_PRICING_RULE.duration
       ,FACT_PRICE.price_id
       ,FACT_PRICE.location_id
       ,FACT_PRICE.created_at
       ,DIM_AVALIABLE_DATES.days

FROM  {{ref('FACT_PRICE')}} AS FACT_PRICE
INNER JOIN {{ref('FACT_PRICING_RULE')}} AS FACT_PRICING_RULE
ON FACT_PRICE.rule_id = FACT_PRICING_RULE.rule_id
INNER JOIN {{ref('DIM_AVALIABLE_DATES')}} AS DIM_AVALIABLE_DATES
ON FACT_PRICING_RULE.rule_id = DIM_AVALIABLE_DATES.rule_id

WHERE FACT_PRICE.location_id = 524686 AND
      FACT_PRICE.CURRENT_FLAG = 'Y' AND 
      DIM_AVALIABLE_DATES.days = 3
      

